name: Test and Deploy My Portfolio to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build CSS
        run: npm run build-css

      - name: Build JS
        run: npm run build-js

      - name: Copy HTML files to dist
        run: mkdir -p dist && cp *.html dist/

      - name: Copy Images to dist
        run: mkdir -p dist/Images && cp -r Images/* dist/Images/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_branch: gh-pages
